<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AppointmentDEMO1.aspx.cs" Inherits="HMS_SYSTEM_29.AppointmentDEMO1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Appointment</title>
    <style>
    body {
        font-family: Arial;
        background: #f4f6f9;
    }

    .container {
        width: 80%;
        margin: auto;
    }

    .nav a {
        margin: 10px;
        text-decoration: none;
        color: #2c3e50;
    }

    .card {
        background: white;
        padding: 20px;
        margin-top: 20px;
        border-radius: 6px;
    }

    input {
        padding: 6px;
        margin: 5px;
        width: 200px;
    }

    .btn {
        background: #e67e22;
        color: white;
        border: none;
        padding: 8px 15px;
        font-size:18px;
    }
</style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">

    <h2>Appointment Management</h2>

    <div class="nav">
        <a href="PatientDEMO.aspx">Patient</a>
        <a href="DocterDEMO.aspx">Doctor</a>
        <a href="AppointmentDEMO1.aspx">Appointment</a>
    </div>

    <div class="card">
        <h3>Book Appointment</h3>

        <asp:TextBox ID="txtPName" runat="server" placeholder="Patient Name" />
        <asp:TextBox ID="txtDName" runat="server" placeholder="Doctor Name" />
        <asp:TextBox ID="txtDate" runat="server" TextMode="Date" />

        <br />
        <asp:Button ID="btnBook" runat="server" Text="Book Appointment" CssClass="btn" OnClick="btnBook_Click"/>
    </div>

    <div class="card">
        <h3>Appointment List</h3>
        <asp:GridView ID="GridView3" runat="server" Width="95%"
            AutoGenerateColumns="False"
            AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True"
            DataKeyNames="ID" Height="154px" OnRowCancelingEdit="GridView3_RowCancelingEdit" OnRowDeleting="GridView3_RowDeleting" OnRowEditing="GridView3_RowEditing" OnRowUpdating="GridView3_RowUpdating">
            <Columns>
                <asp:TemplateField HeaderText="Patient Name">
                    <ItemTemplate>
                        <asp:Label ID="LabelPatientName" runat="server" Text='<%# Eval("A_Name") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBoxPatientName" runat="server" Text='<%# Eval("A_Name") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Doctor Name">
                    <ItemTemplate>
                        <asp:Label ID="LabelDoctorName" runat="server" Text='<%# Eval("A_Docter") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBoxDoctorName" runat="server" Text='<%# Eval("A_Docter") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Date">
                    <ItemTemplate>
                        <asp:Label ID="LabelDate" runat="server" Text='<%# Eval("A_Date") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBoxDate" runat="server" Text='<%# Eval("A_Date") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </div>

</div>
    </form>
</body>
</html>
