<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DocterDEMO.aspx.cs" Inherits="HMS_SYSTEM_29.DocterDEMO" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Doctor Management</title>
    <style>
        body {
            font-family: Arial;
            background: #f4f6f9;
        }

        .container {
            width: 80%;
            margin: auto;
        }

        .nav a {
            margin: 10px;
            text-decoration: none;
            color: #2c3e50;
        }

        .card {
            background: white;
            padding: 20px;
            margin-top: 20px;
            border-radius: 6px;
        }

        input {
            padding: 6px;
            margin: 5px;
            width: 200px;
        }

        .btn {
            background: #3498db;
            color: white;
            border: none;
            padding: 8px 15px;
            font-size:18px
        }
        .auto-style1 {
            background: white;
            padding: 20px;
            margin-top: 20px;
            border-radius: 6px;
            margin-left: 40px;
        }
        .auto-style2 {
            margin-left: 0px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">

            <h2>Doctor Management</h2>

            <div class="nav">
                <a href="PatientDEMO.aspx">Patient</a>
                <a href="DocterDEMO.aspx">Doctor</a>
                <a href="AppointmentDEMO1.aspx">Appointment</a>
            </div>

            <div class="row mb-4">
                <div class="col-md-4">
                    <div class="card p-3">
                        <h5>Total Docter</h5>
                        <asp:Label ID="lblPatients" runat="server" Font-Size="Large" />
                    </div>
                </div>
            <div class="card">
                <h3>Add Doctor</h3>

                <asp:TextBox ID="txtDocName" runat="server" placeholder="Doctor Name" />
                <asp:DropDownList ID="ddlSpec" runat="server" Height="33px" Width="171px">
                    <asp:ListItem>Select Specialisation</asp:ListItem>
                    <asp:ListItem Text="Cardiology" />
                    <asp:ListItem Text="Pediatrics" />
                    <asp:ListItem Text="Obstetrics and Gynecology" />
                    <asp:ListItem Text="Neurology" />
                    <asp:ListItem Text="Oncology" />
                    <asp:ListItem Text="Gastroenterology" />
                    <asp:ListItem Text="Dermatology" />
                    <asp:ListItem Text="Psychiatry" />
                    <asp:ListItem Text="General Surgery" />
                    <asp:ListItem Text="Orthopedic Surgery" />
                    <asp:ListItem Text="Neurosurgery" />
                    <asp:ListItem Text="Plastic Surgery" />
                </asp:DropDownList>

                <asp:DropDownList ID="ddlStatus" runat="server" Height="33px" Width="171px">
                    <asp:ListItem>Choose Status</asp:ListItem>
                    <asp:ListItem Text="Available" />
                    <asp:ListItem Text="Busy" />
                </asp:DropDownList>

                <br />
                <asp:Button ID="btnAdd" runat="server" Text="Add Doctor" CssClass="btn" OnClick="btnAdd_Click" />
            </div>

            <div class="auto-style1">
                <h3>Doctor List</h3>
                <asp:GridView ID="GridView2" runat="server" Width="94%" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Height="177px" CssClass="auto-style2" DataKeyNames="ID" OnRowCancelingEdit="GridView2_RowCancelingEdit" OnRowDeleting="GridView2_RowDeleting" OnRowEditing="GridView2_RowEditing" OnRowUpdating="GridView2_RowUpdating" >
                    <Columns>
                        <asp:TemplateField HeaderText="Doctor Name">
                            <ItemTemplate>
                                <asp:Label ID="LabelName" runat="server" Text='<%# Eval("D_Name") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBoxName" runat="server" Text='<%# Eval("D_Name") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Specialisation">
                            <ItemTemplate>
                                <asp:Label ID="LabelSpec" runat="server" Text='<%# Eval("D_Spec") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBoxSpec" runat="server" Text='<%# Eval("D_Spec") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Status">
                            <ItemTemplate>
                                <asp:Label ID="LabelStatus" runat="server" Text='<%# Eval("D_Status") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBoxStatus" runat="server" Text='<%# Eval("D_Status") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
            </div>
</div>
        </div>
    </form>
</body>
</html>
