<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PatientDEMO.aspx.cs" Inherits="HMS_SYSTEM_29.PatientDEMO" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
        <title>Patient Management</title>

    <style>
        body { font-family: Arial; background:#f4f6f9; }
        .container { width: 80%; margin: auto; }
        .nav a { margin: 10px; text-decoration:none; color:#2c3e50; }
        .card { background:white; padding:20px; margin-top:20px; border-radius:6px; }
        input, select { padding:6px; margin:5px; width:200px; }
        .btn { background:#1abc9c; color:white; border:none; padding:8px 15px; font-size:20px }
    </style>
     <script>
         Swal.fire({
             title: 'Success!',
             text: 'Action completed.',
             icon: 'success',
             confirmButtonText: 'Cool'
         });
     </script>
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">

    <h2>Patient Management</h2>

    <div class="nav">
        <a href="PatientDEMO.aspx">Patient</a>
        <a href="DocterDEMO.aspx">Doctor</a>
        <a href="AppointmentDEMO1.aspx">Appointment</a>
    </div>

    <!-- Dashboard -->
    <div class="row mb-4">
        <div class="col-md-4">
            <div class="card p-3">
                <h5>Total Patients</h5>
                <asp:Label ID="lblPatients" runat="server" Font-Size="Large" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="card p-3">
                <h5>Appointments</h5>
                <asp:Label ID="lblAppointments" runat="server" Font-Size="Large" />
            </div>
        </div>
    </div>

    <div class="card">
        <h3>Register Patient</h3>

        <asp:TextBox ID="txtName" runat="server" placeholder="Name" />
        <asp:TextBox ID="txtAge" runat="server" placeholder="Age" />

        <asp:DropDownList ID="ddlGender" runat="server">
            <asp:ListItem Text="Select Gender"/>
            <asp:ListItem Text="Male" />
            <asp:ListItem Text="Female" />
        </asp:DropDownList>

        <asp:TextBox ID="txtPhone" runat="server" placeholder="Phone" />
        <%--<asp:TextBox ID="txtAddress" runat="server" placeholder="Address" />--%>

        <br />
        <asp:Button ID="btnSave" runat="server" Text="Register" CssClass="btn" OnClick="btnSave_Click" />
    </div>
    <div class="card">
        <h3>Patient List</h3>
        <asp:GridView ID="GridViewpatient" runat="server" Width="97%" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Height="175px"
            OnRowCancelingEdit="GridViewpatient_RowCancelingEdit"
            OnRowDeleting="GridViewpatient_RowDeleting"
            OnRowEditing="GridViewpatient_RowEditing"
            OnRowUpdating="GridViewpatient_RowUpdating"
            DataKeyNames="Id">
            <Columns>
                <asp:TemplateField HeaderText="Name">
                    <ItemTemplate>
                        <asp:Label ID="LabelName" runat="server" Text='<%# Eval("P_Name") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBoxName" runat="server" Text='<%# Eval("P_Name") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Age">
                    <ItemTemplate>
                        <asp:Label ID="LabelAge" runat="server" Text='<%# Eval("P_Age") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBoxAge" runat="server" Text='<%# Eval("P_Age") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Gender">
                    <ItemTemplate>
                        <asp:Label ID="LabelGender" runat="server" Text='<%# Eval("P_Gender") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBoxGender" runat="server" Text='<%# Eval("P_Gender") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Phone">
                    <ItemTemplate>
                        <asp:Label ID="LabelMobile" runat="server" Text='<%# Eval("P_Mobile") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBoxMobile" runat="server" Text='<%# Eval("P_Mobile") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </div>

</div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</body>
</html>
